// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWO_Book_Store_BE.Model;

#nullable disable

namespace SWO_Book_Store_BE.Migrations
{
    [DbContext(typeof(BookDBContext))]
    [Migration("20240722074046_mysqlInit")]
    partial class mysqlInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SWO_Book_Store_BE.Model.BookModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("item")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<string>("unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("id");

                    b.ToTable("BookModel");
                });
#pragma warning restore 612, 618
        }
    }
}
